[package]
edition = "2021"
name = "modelfox_app_production_stats"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.6", features = ["serde"] }
fnv = "1"
indexmap = { version = "1.6", features = ["serde-1"] }
itertools = "0.10"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.5", default-features = false, features = ["any", "chrono", "postgres", "runtime-tokio-rustls", "sqlite"] }
modelfox_app_date_window = { path = "../date_window" }
modelfox_app_monitor_event = { path = "../monitor_event" }
modelfox_metrics = { path = "../../metrics" }
modelfox_model = { path = "../../model" }
modelfox_text = { path = "../../text" }
modelfox_zip = { path = "../../zip" }

[dev-dependencies]
insta = "1"
