[package]
edition = "2021"
name = "tangram_node"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
name = "tangram_node"
path = "lib.rs"

[build-dependencies]
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
memmap = "0.7"
node_api = { version = "0.5", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
tangram_core = { path = "../../../crates/core" }
tangram_model = { path = "../../../crates/model" }
