[package]
authors = ["ModelFox <root@modelfox.dev"]
description = "ModelFox makes it easy for programmers to train, deploy, and monitor machine learning models."
documentation = "https://docs.rs/modelfox"
edition = "2021"
homepage = "https://github.com/modelfoxdotdev/modelfox"
license = "MIT"
name = "modelfox_metrics"
publish = true
repository = "https://github.com/modelfoxdotdev/modelfox"
version = "0.8.0"

[lib]
path = "lib.rs"

[dev-dependencies]
insta = "1"

[dependencies]
itertools = "0.10"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
modelfox_zip = { version = "0.8.0", path = "../zip" }
