[package]
authors = ["ModelFox <root@modelfox.dev"]
description = "ModelFox makes it easy for programmers to train, deploy, and monitor machine learning models."
documentation = "https://docs.rs/modelfox"
edition = "2021"
homepage = "https://github.com/modelfoxdotdev/modelfox"
license = "MIT"
name = "modelfox_table"
publish = true
repository = "https://github.com/modelfoxdotdev/modelfox"
version = "0.8.0"

[lib]
path = "lib.rs"

[dev-dependencies]
insta = "1"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
csv = "1"
fast-float = "0.2"
fnv = "1"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
modelfox_progress_counter = { version = "0.8.0", path = "../progress_counter" }
modelfox_zip = { version = "0.8.0", path = "../zip" }
