[workspace]
members = [
	"crates/*",
	"languages/c",
	"languages/elixir",
	"languages/javascript/node",
	"languages/javascript/wasm",
	"languages/python",
	"languages/rust",
	"languages/rust/examples/*",
]

[profile.dev.build-override]
debug-assertions = false
opt-level = 3
overflow-checks = false

[profile.release]
lto = true
strip = true

[patch.crates-io]
sunfish = { git = "https://github.com/tangramdotdev/sunfish" }
erl_nif = { git = "https://github.com/tangramdotdev/erl_nif" }
node_api = { git = "https://github.com/tangramdotdev/node_api" }
