[package]
edition = "2021"
name = "modelfox_www_content"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
pinwheel = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sunfish = "0.7"
modelfox_ui = { path = "../../ui" }
