[package]
edition = "2021"
license = "MIT"
name = "modelfox_license"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[[bin]]
name = "modelfox_license"
path = "main.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
base64 = "0.13"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3", features = ["derive"] }
digest = "0.10"
duct = "0.13"
indoc = "1"
pem = "1"
rand = "0.8"
rsa = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
modelfox_id = { path = "../id" }
