[package]
edition = "2021"
name = "tangram_www_index_client"
publish = false
version = "0.0.0"

[[bin]]
name = "tangram_www_index_client"
path = "main.rs"

[dependencies]
pinwheel = "0.2"
tangram_charts = { path = "../../../../charts" }
tangram_ui = { path = "../../../../ui" }
tangram_www_index_common = { path = "../common" }
web-sys = "0.3"
