[package]
edition = "2021"
name = "modelfox_ui"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
console_error_panic_hook = "0.1"
convert_case = "0.5"
indoc = "1"
num = "0.4"
once_cell = "1"
percent-encoding = "2"
pinwheel = "0.2"
pulldown-cmark = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
modelfox_charts = { path = "../charts" }
modelfox_finite = { path = "../finite" }
modelfox_number_formatter = { path = "../number_formatter" }
tracing = "0.1"
tracing-wasm = "0.2"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
web-sys = { version = "0.3", features = [
  "CanvasRenderingContext2d",
  "console",
  "CssStyleDeclaration",
  "Document",
  "DomRect",
  "DomStringMap",
  "Element",
  "EventListener",
  "EventTarget",
  "File",
  "FileList",
  "HtmlCanvasElement",
  "HtmlCollection",
  "HtmlElement",
  "HtmlFormElement",
  "HtmlInputElement",
  "HtmlSelectElement",
  "InputEvent",
  "MediaQueryList",
  "MouseEvent",
  "Node",
  "NodeList",
  "Performance",
  "Text",
  "TextMetrics",
  "Touch",
  "TouchEvent",
  "TouchList",
  "Window",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tree-sitter-highlight = "0.20"
tree-sitter-javascript = "0.20"
tree-sitter-rust = "0.20"
