[package]
authors = ["Tangram <root@tangram.dev"]
description = "Tangram makes it easy for programmers to train, deploy, and monitor machine learning models."
documentation = "https://docs.rs/tangram"
edition = "2021"
homepage = "https://github.com/tangramdotdev/tangram"
license = "MIT"
name = "tangram_tree"
publish = true
repository = "https://github.com/tangramdotdev/tangram"
version = "0.7.0"


[lib]
path = "lib.rs"

[features]
default = []
timing = []

[[bin]]
name = "tangram_tree_benchmarks"
path = "benchmarks/main.rs"

[[bin]]
name = "tangram_tree_benchmark_allstate"
path = "benchmarks/allstate.rs"

[[bin]]
name = "tangram_tree_benchmark_boston"
path = "benchmarks/boston.rs"

[[bin]]
name = "tangram_tree_benchmark_census"
path = "benchmarks/census.rs"

[[bin]]
name = "tangram_tree_benchmark_flights"
path = "benchmarks/flights.rs"

[[bin]]
name = "tangram_tree_benchmark_heart_disease"
path = "benchmarks/heart_disease.rs"

[[bin]]
name = "tangram_tree_benchmark_higgs"
path = "benchmarks/higgs.rs"

[[bin]]
name = "tangram_tree_benchmark_iris"
path = "benchmarks/iris.rs"

[dependencies]
bitvec = "1"
buffalo = { version = "0.3", features = ["bitvec", "ndarray_0_15"] }
clap = { version = "3", features = ["derive"] }
itertools = "0.10"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
rayon = "1.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tangram_finite = { version = "0.7.0", path = "../finite" }
tangram_kill_chip = { version = "0.7.0", path = "../kill_chip" }
tangram_metrics = { version = "0.7.0", path = "../metrics" }
tangram_progress_counter = { version = "0.7.0", path = "../progress_counter" }
tangram_table = { version = "0.7.0", path = "../table" }
tangram_zip = { version = "0.7.0", path = "../zip" }
