[package]
authors = ["ModelFox <root@modelfox.dev"]
description = "ModelFox makes it easy for programmers to train, deploy, and monitor machine learning models."
documentation = "https://docs.rs/modelfox"
edition = "2021"
homepage = "https://github.com/modelfoxdotdev/modelfox"
license = "MIT"
name = "modelfox_tree"
publish = true
repository = "https://github.com/modelfoxdotdev/modelfox"
version = "0.8.0"


[lib]
path = "lib.rs"

[features]
default = []
timing = []

[[bin]]
name = "modelfox_tree_benchmarks"
path = "benchmarks/main.rs"

[[bin]]
name = "modelfox_tree_benchmark_allstate"
path = "benchmarks/allstate.rs"

[[bin]]
name = "modelfox_tree_benchmark_boston"
path = "benchmarks/boston.rs"

[[bin]]
name = "modelfox_tree_benchmark_census"
path = "benchmarks/census.rs"

[[bin]]
name = "modelfox_tree_benchmark_flights"
path = "benchmarks/flights.rs"

[[bin]]
name = "modelfox_tree_benchmark_heart_disease"
path = "benchmarks/heart_disease.rs"

[[bin]]
name = "modelfox_tree_benchmark_higgs"
path = "benchmarks/higgs.rs"

[[bin]]
name = "modelfox_tree_benchmark_iris"
path = "benchmarks/iris.rs"

[dependencies]
bitvec = "1"
buffalo = { version = "0.4", features = ["bitvec", "ndarray"] }
clap = { version = "3", features = ["derive"] }
itertools = "0.10"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
rayon = "1.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
modelfox_finite = { version = "0.8.0", path = "../finite" }
modelfox_kill_chip = { version = "0.8.0", path = "../kill_chip" }
modelfox_metrics = { version = "0.8.0", path = "../metrics" }
modelfox_progress_counter = { version = "0.8.0", path = "../progress_counter" }
modelfox_table = { version = "0.8.0", path = "../table" }
modelfox_zip = { version = "0.8.0", path = "../zip" }
