[package]
edition = "2021"
rust-version = "1.56"
name = "tangram_app_monitor_event"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tangram_finite = { path = "../../finite" }
tangram_id = { path = "../../id" }
