[package]
edition = "2021"
name = "modelfox_www_docs_index_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
pinwheel = "0.2"
modelfox_app_core = { path = "../../../../../app/core" }
modelfox_www_ui = { path = "../../../../ui" }
modelfox_www_layouts = { path = "../../../../layouts" }
sunfish = "0.7"
modelfox_ui = { path = "../../../../../ui" }
