[package]
edition = "2021"
name = "tangram_www_docs_index_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
pinwheel = "0.2"
tangram_app_core = { path = "../../../../../app/core" }
tangram_www_ui = { path = "../../../../ui" }
tangram_www_layouts = { path = "../../../../layouts" }
sunfish = "0.3"
tangram_ui = { path = "../../../../../ui" }
