[package]
edition = "2021"
name = "modelfox_dev"
publish = false
version = "0.0.0"

[[bin]]
name = "modelfox_dev"
path = "main.rs"

[dependencies]
clap = { version = "3", features = ["derive"] }
sunfish = "0.7"
tokio = { version = "1", features = ["full"] }
