[package]
edition = "2021"
name = "tangram_app_production_metrics"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.6", features = ["serde"] }
ndarray = { version = " 0.15", features = ["rayon"] }
num = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.5", default-features = false, features = ["any", "chrono", "postgres", "runtime-tokio-rustls", "sqlite"] }
tangram_app_date_window = { path = "../date_window" }
tangram_app_monitor_event = { path = "../monitor_event" }
tangram_app_production_stats = { path = "../production_stats" }
tangram_model = { path = "../../model" }
tangram_zip = { path = "../../zip" }

[dev-dependencies]
insta = "1"
