[package]
edition = "2021"
name = "modelfox_www_docs_getting_started_inspect_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
num = "0.4"
pinwheel = "0.2"
sunfish = "0.7"
modelfox_ui = { path = "../../../../../../ui" }
modelfox_www_docs_inspect_common = { path = "../common" }
modelfox_www_layouts = { path = "../../../../../layouts" }
modelfox_www_ui = { path = "../../../../../ui" }
