[package]
authors = ["ModelFox <root@modelfox.dev"]
description = "Make predictions with a ModelFox model from your Rust app. Learn more at https://www.modelfox.dev/."
documentation = "https://docs.rs/modelfox"
edition = "2021"
homepage = "https://github.com/modelfoxdotdev/modelfox"
license = "MIT"
name = "modelfox_macro"
publish = true
repository = "https://github.com/modelfoxdotdev/modelfox"
version = "0.7.0"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
