[package]
edition = "2021"
name = "tangram_app_track_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
memmap = "0.7"
num = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.5", default-features = false, features = ["any", "chrono", "postgres", "runtime-tokio-rustls", "sqlite"] }
sunfish = "0.5"
tangram_app_context = { path = "../../../context" }
tangram_app_core = { path = "../../../core" }
tangram_app_monitor_event = { path = "../../../monitor_event" }
tangram_core = { path = "../../../../core" }
tangram_id = { path = "../../../../id" }
tangram_model = { path = "../../../../model" }
tracing = "0.1"
url = { version = "2", features = ["serde"] }
