[package]
edition = "2021"
name = "modelfox_wasm"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
name = "modelfox_wasm"
path = "lib.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde-wasm-bindgen = "0.4"
modelfox_core = { path = "../../../crates/core" }
modelfox_model = { path = "../../../crates/model" }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
