author = "ModelFox"
author_email = "root@modelfox.dev"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
]
description = "README.md"
description_content_type = "text/markdown"
license = "LICENSE"
name = "modelfox"
summary = "ModelFox for Python"
version = "0.8.0"

[project_url]
homepage = "https://modelfox.dev"
