[package]
edition = "2021"
license = "MIT"
name = "modelfox_number_formatter"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
num = "0.4"
serde = { version = "1", features = ["derive"] }
