[package]
edition = "2021"
name = "modelfox_app_training_class_metrics_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
num = "0.4"
pinwheel = "0.2"
serde = { version = "1", features = ["derive"] }
serde_urlencoded = "0.7"
sunfish = "0.7"
modelfox_app_context = { path = "../../../../../../../../context" }
modelfox_app_core = { path = "../../../../../../../../core" }
modelfox_app_layouts = { path = "../../../../../../../../layouts" }
modelfox_app_ui = { path = "../../../../../../../../ui" }
modelfox_core = { path = "../../../../../../../../../core" }
modelfox_id = { path = "../../../../../../../../../id" }
modelfox_model = { path = "../../../../../../../../../model" }
modelfox_ui = { path = "../../../../../../../../../ui" }
