[package]
edition = "2021"
name = "tangram_app_training_stats_column_client"
publish = false
version = "0.0.0"

[[bin]]
name = "tangram_app_training_stats_column_client"
path = "main.rs"

[dependencies]
console_error_panic_hook = "0.1"
pinwheel = "0.2"
tangram_charts = { path = "../../../../../../../../../../charts" }
tangram_ui = { path = "../../../../../../../../../../ui" }
wasm-bindgen = "0.2"
web-sys = "0.3"
