[package]
edition = "2021"
name = "modelfox_www_docs_getting_started_inspect_client"
publish = false
version = "0.0.0"

[[bin]]
name = "modelfox_www_docs_getting_started_inspect_client"
path = "main.rs"

[dependencies]
console_error_panic_hook = "0.1"
modelfox_charts = { path = "../../../../../../charts" }
modelfox_ui = { path = "../../../../../../ui" }
modelfox_www_docs_inspect_common = { path = "../common" }
pinwheel = "0.2"
wasm-bindgen = "0.2"
web-sys = "0.3"
