[package]
edition = "2021"
name = "tangram_www_docs_getting_started_inspect_client"
publish = false
version = "0.0.0"

[[bin]]
name = "tangram_www_docs_getting_started_inspect_client"
path = "main.rs"

[dependencies]
console_error_panic_hook = "0.1"
tangram_charts = { path = "../../../../../../charts" }
tangram_ui = { path = "../../../../../../ui" }
tangram_www_docs_inspect_common = { path = "../common" }
pinwheel = "0.2"
wasm-bindgen = "0.2"
web-sys = "0.3"
