[package]
edition = "2021"
name = "modelfox_app_context"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
sunfish = "0.7"
modelfox_app_core = { path = "../core" }
