[package]
edition = "2021"
name = "tangram_app_training_grid_common"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
num = "0.4"
pinwheel = "0.2"
tangram_app_core = { path = "../../../../../../../core" }
tangram_charts = { path = "../../../../../../../../charts" }
tangram_core = { path = "../../../../../../../../core" }
tangram_id = { path = "../../../../../../../../id" }
tangram_model = { path = "../../../../../../../../model" }
tangram_ui = { path = "../../../../../../../../ui" }
