[package]
edition = "2021"
name = "modelfox_app_playground_common"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
pinwheel = "0.2"
serde = { version = "1", features = ["derive"] }
modelfox_charts = { path = "../../../../../../../../charts" }
