[package]
edition = "2021"
name = "modelfox_app_model_index_client"
publish = false
version = "0.0.0"

[[bin]]
name = "modelfox_app_model_index_client"
path = "main.rs"

[dependencies]
console_error_panic_hook = "0.1"
pinwheel = "0.2"
modelfox_charts = { path = "../../../../../../../../charts" }
modelfox_ui = { path = "../../../../../../../../ui" }
wasm-bindgen = "0.2"
