[package]
edition = "2021"
license = "UNLICENSED"
name = "modelfox_www"
publish = false
version = "0.0.0"

[[bin]]
name = "modelfox_www"
path = "main.rs"

[features]
default = [
  "modelfox_www_about_server",
  "modelfox_www_benchmarks_client",
  "modelfox_www_benchmarks_server",
  "modelfox_www_blog_index_server",
  "modelfox_www_blog_server",
  "modelfox_www_docs_getting_started_index_server",
  "modelfox_www_docs_getting_started_inspect_client",
  "modelfox_www_docs_getting_started_inspect_server",
  "modelfox_www_docs_getting_started_monitor_client",
  "modelfox_www_docs_getting_started_monitor_server",
  "modelfox_www_docs_getting_started_predict_cli_server",
  "modelfox_www_docs_getting_started_predict_elixir_server",
  "modelfox_www_docs_getting_started_predict_go_server",
  "modelfox_www_docs_getting_started_predict_index_server",
  "modelfox_www_docs_getting_started_predict_javascript_server",
  "modelfox_www_docs_getting_started_predict_php_server",
  "modelfox_www_docs_getting_started_predict_python_server",
  "modelfox_www_docs_getting_started_predict_ruby_server",
  "modelfox_www_docs_getting_started_predict_rust_server",
  "modelfox_www_docs_getting_started_train_server",
  "modelfox_www_docs_guide_server",
  "modelfox_www_docs_index_server",
  "modelfox_www_docs_install_server",
  "modelfox_www_docs_internals_server",
  "modelfox_www_index_client",
  "modelfox_www_index_server",
  "modelfox_www_pricing_server",
]

[build-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
sunfish = "0.7"
modelfox_www_benchmarks_client = { path = "routes/benchmarks/client", optional = true, artifact = "bin", target = "wasm32-unknown-unknown" }
modelfox_www_index_client = { path = "routes/index/client", optional = true, artifact = "bin", target = "wasm32-unknown-unknown" }
modelfox_www_docs_getting_started_monitor_client = {path = "routes/docs/getting_started/monitor/client", optional = true, artifact = "bin", target = "wasm32-unknown-unknown" }
modelfox_www_docs_getting_started_inspect_client = {path = "routes/docs/getting_started/inspect/client", optional = true, artifact = "bin", target = "wasm32-unknown-unknown" }

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
clap = { version = "3", features = ["derive"] }
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sunfish = "0.7"
modelfox_id = { path = "../id" }
modelfox_serve = { path = "../serve" }
modelfox_www_content = { path = "content" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

modelfox_www_about_server = { path = "routes/about/server", optional = true }
modelfox_www_benchmarks_server = { path = "routes/benchmarks/server", optional = true }
modelfox_www_blog_index_server = { path = "routes/blog/index/server", optional = true }
modelfox_www_blog_server = { path = "routes/blog/_/index/server", optional = true }
modelfox_www_docs_getting_started_index_server = { path = "routes/docs/getting_started/index/server", optional = true }
modelfox_www_docs_getting_started_inspect_server = { path = "routes/docs/getting_started/inspect/server", optional = true }
modelfox_www_docs_getting_started_monitor_server = { path = "routes/docs/getting_started/monitor/server", optional = true }
modelfox_www_docs_getting_started_predict_cli_server = { path = "routes/docs/getting_started/predict/cli/server", optional = true }
modelfox_www_docs_getting_started_predict_elixir_server = { path = "routes/docs/getting_started/predict/elixir/server", optional = true }
modelfox_www_docs_getting_started_predict_go_server = { path = "routes/docs/getting_started/predict/go/server", optional = true }
modelfox_www_docs_getting_started_predict_index_server = { path = "routes/docs/getting_started/predict/index/server", optional = true }
modelfox_www_docs_getting_started_predict_javascript_server = { path = "routes/docs/getting_started/predict/javascript/server", optional = true }
modelfox_www_docs_getting_started_predict_php_server = { path = "routes/docs/getting_started/predict/php/server", optional = true }
modelfox_www_docs_getting_started_predict_python_server = { path = "routes/docs/getting_started/predict/python/server", optional = true }
modelfox_www_docs_getting_started_predict_ruby_server = { path = "routes/docs/getting_started/predict/ruby/server", optional = true }
modelfox_www_docs_getting_started_predict_rust_server = { path = "routes/docs/getting_started/predict/rust/server", optional = true }
modelfox_www_docs_getting_started_train_server = { path = "routes/docs/getting_started/train/server", optional = true }
modelfox_www_docs_guide_server = { path = "routes/docs/guides/_/server", optional = true }
modelfox_www_docs_index_server = { path = "routes/docs/index/server", optional = true }
modelfox_www_docs_install_server = { path = "routes/docs/install/server", optional = true }
modelfox_www_docs_internals_server = { path = "routes/docs/internals/_/server", optional = true }
modelfox_www_index_server = { path = "routes/index/server", optional = true }
modelfox_www_pricing_server = { path = "routes/pricing/server", optional = true }
