[package]
edition = "2021"
license = "UNLICENSED"
name = "tangram_app_migrations"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
futures = "0.3"
once_cell = "1"
sqlx = { version = "0.5", default-features = false, features = ["any", "chrono", "postgres", "runtime-tokio-rustls", "sqlite"] }
tangram_zip = { path = "../../zip" }
