[package]
edition = "2021"
name = "modelfox_app_production_stats_column_client"
publish = false
version = "0.0.0"

[[bin]]
name = "modelfox_app_production_stats_column_client"
path = "main.rs"

[dependencies]
pinwheel = "0.2"
modelfox_charts = { path = "../../../../../../../../../../charts" }
modelfox_ui = { path = "../../../../../../../../../../ui" }
web-sys = "0.3"
