[package]
edition = "2021"
name = "modelfox_app_tuning_client"
publish = false
version = "0.0.0"

[[bin]]
name = "modelfox_app_tuning_client"
path = "main.rs"

[dependencies]
pinwheel = "0.2"
modelfox_app_tuning_common = { path = "../common" }
modelfox_ui = { path = "../../../../../../../../ui" }
web-sys = "0.3"
