[package]
edition = "2021"
name = "tangram_elixir"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
name = "tangram_elixir"
path = "lib.rs"

[dependencies]
erl_nif = { version = "0.4", features = ["serde"] }
memmap = "0.7"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
tangram_core = { path = "../../crates/core" }
anyhow = { version = "1", features = ["backtrace"] }
tangram_model = { path = "../../crates/model" }
