[package]
edition = "2021"
name = "modelfox_www_blog_index_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
pinwheel = "0.2"
modelfox_ui = { path = "../../../../../ui" }
sunfish = "0.7"
modelfox_www_content = { path = "../../../../content" }
modelfox_www_layouts = { path = "../../../../layouts" }
