[package]
edition = "2021"
name = "modelfox_app_core"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dev-dependencies]
insta = "1"
modelfox = { path = "../../../languages/rust" }
modelfox_serve = { path = "../../serve" }
tracing-test = "0.2"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bytes = "1"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.6", features = ["serde"] }
dirs = "4"
futures = "0.3"
fnv = "1"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
indexmap = { version = "1.6", features = ["serde-1"] }
itertools = "0.10"
lettre = { version = "0.10.0-rc.2", default-features = false, features = ["builder", "hostname", "smtp-transport", "tokio1-rustls-tls"] }
memmap = "0.7"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
rand = "0.8"
rust-s3 = { version = "0.30", default-features = false, features = ["tokio-rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.5", default-features = false, features = ["any", "chrono", "postgres", "runtime-tokio-rustls", "sqlite"] }
sunfish = "0.7"
modelfox_app_migrations = { path = "../migrations" }
modelfox_app_monitor_event = { path = "../monitor_event" }
modelfox_app_production_metrics = { path = "../production_metrics" }
modelfox_app_production_stats = { path = "../production_stats" }
modelfox_core = { path = "../../core" }
modelfox_finite = { path = "../../finite" }
modelfox_id = { path = "../../id" }
modelfox_metrics = { path = "../../metrics" }
modelfox_model = { path = "../../model" }
modelfox_table = { path = "../../table" }
modelfox_text = { path = "../../text" }
modelfox_zip = { path = "../../zip" }
time = { version = "0.3", features = ["formatting", "macros"] }
tokio = { version = "1", features = ["full", "time", "test-util"] }
tracing = "0.1"
url = { version = "2", features = ["serde"] }
