[package]
edition = "2021"
name = "modelfox_www_index_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
pinwheel = "0.2"
futures = "0.3"
modelfox_charts = { path = "../../../../charts" }
sunfish = "0.7"
modelfox_ui = { path = "../../../../ui" }
modelfox_finite = { path = "../../../../finite" }
modelfox_www_ui = { path = "../../../ui" }
modelfox_www_index_common = { path = "../common" }
modelfox_www_layouts = { path = "../../../layouts" }
