[package]
edition = "2021"
name = "tangram_www_docs_inspect_common"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
tangram_www_index_common = { path = "../../../../index/common" }
