[package]
edition = "2021"
name = "modelfox_www_docs_getting_started_index_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
pinwheel = "0.2"
modelfox_www_layouts = { path = "../../../../../layouts" }
sunfish = "0.7"
modelfox_ui = { path = "../../../../../../ui" }
