[package]
authors = ["ModelFox <root@modelfox.dev"]
description = "Make predictions with a ModelFox model from your Rust app. Learn more at https://www.modelfox.dev/."
documentation = "https://docs.rs/modelfox"
edition = "2021"
homepage = "https://github.com/modelfoxdotdev/modelfox"
license = "MIT"
name = "modelfox"
publish = true
repository = "https://github.com/modelfoxdotdev/modelfox"
version = "0.7.0"

[lib]
path = "lib.rs"

[features]
default = []
tokio_1 = ["tokio"]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
chrono = { version = "0.4", features = ["serde"] }
memmap = "0.7"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
modelfox_core = { version = "0.7.0", path = "../../crates/core" }
modelfox_macro = { version = "0.7.0", path = "macro" }
modelfox_model = { version = "0.7.0", path = "../../crates/model" }
tokio = { version = "1", features = ["full"], optional = true }
url = { version = "2", features = ["serde"] }
