[package]
edition = "2021"
license = "MIT"
name = "modelfox_example_basic"
publish = false
version = "0.0.0"

[[bin]]
name = "modelfox_example_basic"
path = "main.rs"

[dependencies]
modelfox = { version = "0.7.0", path = "../../" }
