[package]
edition = "2021"
name = "modelfox_app_new_monitor_client"
publish = false
version = "0.0.0"

[[bin]]
name = "modelfox_app_new_monitor_client"
path = "main.rs"

[dependencies]
modelfox_ui = { path = "../../../../../../../../../ui" }
web-sys = "0.3"
