[package]
edition = "2021"
name = "modelfox_app_training_class_metrics_client"
publish = false
version = "0.0.0"

[[bin]]
name = "modelfox_app_training_class_metrics_client"
path = "main.rs"

[dependencies]
modelfox_ui = { path = "../../../../../../../../../ui" }
