[package]
edition = "2021"
name = "modelfox_app_training_metrics_precision_recall_client"
publish = false
version = "0.0.0"

[[bin]]
name = "modelfox_app_training_metrics_precision_recall_client"
path = "main.rs"

[dependencies]
pinwheel = "0.2"
modelfox_charts = { path = "../../../../../../../../../charts" }
modelfox_ui = { path = "../../../../../../../../../ui" }
