[package]
edition = "2021"
name = "modelfox_www_benchmarks_common"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
futures-signals = "0.3"
num = "0.4"
pinwheel = "0.2"
serde = { version = "1", features = ["derive"] }
modelfox_ui = { path = "../../../../ui" }
modelfox_charts = { path = "../../../../charts" }
tracing = "0.1"
